OPENAI_API_KEY = "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"


SHODAN_API_KEY = "PK3vNoYPVmVeAwcMGrLE9mgdtL9Ejd0n"
